version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production 
    env_file:
      - .env 
    restart: always 

  nginx:
    image: nginx:latest 
    ports:
      - '8080:80'   
      - '8443:443' 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
      - ./mycv:/etc/nginx/sites-available/mycv 
      - /etc/letsencrypt:/etc/letsencrypt 
    depends_on:
      - app
    restart: always
